### ISSUE TITLE
Cannot see the addin button after hitting F5

### ISSUE THREAD

**Issue by mvpkenlin** [OfficeDev/Office-Add-in-ASPNET-SSO#18]
I open the sln with the complete projects. I then following the instruction on https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet to completed the App registration, replace the values. And then hit F5. Powerpoint runs but no addin button could be found. And there is no error on the error list. What could I do to fix now?

**Comment by Rick-Kirkham** [comment]
Try deleting the Office cache. See instructions here: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest. Scroll down to **Clear the Office cache**.

Also, what version of Visual Studio are you using?

**Comment by citems** [comment]
I have the same problem.  I'm using Visual Studio Community 2017 15.5.7.  Office is at version 1801 Build 9001.2171.  Clearing the office cache didn't help.  I was able to create a dev add-in for Outlook fine earlier.  I haven't spent much time investigating, but I noticed the FunctionFile.html is missing from the project.

**Comment by Rick-Kirkham** [comment]
I can reproduce this on VS Enterprise 2017 15.6.0, but it did not happen on VS Enterprise 2017 15.5.0. It appears that something broke in how VS sideloads the add-in. I will report this. In the meantime, the workaround is to manually [sideload the manifest](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins). To get the version of the manifest that you should sideload, press F5 in VS. Then get the manifest XML file at this path in the project: ...Office-Add-in-ASP.NET-SSO\Complete\Office-Add-in-ASPNET-SSO\bin\Debug\OfficeAppManifests

**Comment by Rick-Kirkham** [comment]
The bug is that the tools are not generating the special version of the manifest file that is supposed to go into the folder at Office-Add-in-ASP.NET-SSO\Complete\Office-Add-in-ASPNET-SSO\bin\Debug\OfficeAppManifests. This is basically the same manifest, but the "~remoteUrl" token is replaced with the actual domain: https://localhost:44355. 

So my workaround above isn't going to work for those of you who don't happen to have an old copy of the special version. For you the folder is going to be empty. What you need to do, until this is fixed, is manually copy your manifest into that folder. Then manually replace the "~remoteUrl" token wherever it appears in the file with the actual domain: "https://localhost:44355". One last thing: change the name of the file from `existing-file-name.xml` to `existing-file-nameManifest.xml`. In other words, insert the string "Manifest" just before the "." in the file name. 

If you do, this you should not need to manually sideload. When VS finds your manually created file in that folder, it will sideload for you. So F5 should work again. 

Until the bug is fixed, IF YOU MAKE ANY CHANGES IN YOUR MANIFEST, YOU WILL HAVE TO REPEAT THE PROCESS OF MANUALLY CREATING THE SPECIAL VERSION.

**Comment by Rick-Kirkham** [comment]
@mvpkenlin @citems 
I think I've found a fix that doesn't require the work around. There's a new *.sln file in the root of the Complete folder. Please download it and copy it over the previous version. That should fix it.

**Comment by citems** [comment]
@Rick-Kirkham 
That did the trick!  Thank you, sir.
