### ISSUE TITLE
Office add ins SSO return 502

### ISSUE THREAD

**Issue by seng1** [OfficeDev/Office-Add-in-ASPNET-SSO#34]
I have implemented office add ins SSO with asp.net. I have deploy our the application to our office 365. It was working fine the first week and after a few week later it return 502.
 
![Capture](https://user-images.githubusercontent.com/3612176/58485718-c0b5f480-818e-11e9-94f7-66d125763be3.PNG)
![Capture](https://user-images.githubusercontent.com/3612176/58485785-e3e0a400-818e-11e9-81dd-89a511858258.PNG)

**Comment by Rick-Kirkham** [comment]
**EDIT**: It looks like GitHub's beta feature for transferrring issues to another repo is not working today. Could I ask you to recreate this issue at https://github.com/OfficeDev/office-js/issues ? Thanks.

**ORIGINAL ANSWER:**
Since this is a problem with SSO in general and not this particular sample, I'm going to move this issue to the office-js repo. 

Please note that SSO is turned off on Office builds that reach the semi-annual channel. What Office build are your users on?

**Comment by seng1** [comment]
I was using Firefox to debug. for our first week of deploy it work perfectly. We follow your instruction Office-Add-in-ASPNET-SSO and attachment above is related to Asp.net. I am a bit surprising when submit the issue related to ASP.NET SSO, it automatically close and unrelated.
