### ISSUE TITLE
Never authorized

### ISSUE THREAD

**Issue by RusselRillema** [OfficeDev/Office-Add-in-ASPNET-SSO#38]
Hi
I have tried to configure this myself as well as just adding the necessary configs to the complete project but for some reason I am never authorized.
I did have to change ConfidentialClientApplication to use ConfidentialClientApplicationBuilder as ConfidentialClientApplication is obsolete but this code is in the ValuesController that I am not authorised to use anyway so it should be the cause of the issue.
Part of what I see in the output when calling the Get method is
"responseCode":"401","url":"https://localhost:44355/api/values"
If I remove the [Authorize] tag it does hit the Get method but then it can't find the ClaimsPrincipal on the first line in the get method.
I assume fixing whatever is causing me to not be authorized will make the ClaimsPrincipal part work too.
Any ideas on where I can look to see why I am not authorised?

**Comment by Rick-Kirkham** [comment]
This sample is going to change significantly later today.  I don't recommend working with the current version any longer. Please re-clone the repo tomorrow. You can get a preview of the changes by looking at the `fallback` branch.

**Comment by RusselRillema** [comment]
Oh great thanks!

**Comment by RusselRillema** [comment]
Hi 
Sorry for the long message...

I have downloaded the current version, updated 8 hours ago, and run through all the configs.
I still have the Authorization issue however if I use UseWindowsAzureActiveDirectoryBearerAuthentication it works.
I am using Single Tenant for the time being so this may very well have something to do with the issue.
Are there any security risks or potential future issues to me using UseWindowsAzureActiveDirectoryBearerAuthentication?


Just a couple other things to mention...
Firstly, 
In the documentation under the "Configure the solution" section
number 5 says
"Still in the web.config, replace the placeholder tenant_GUID_here in the ida:Issuer value with the Directory (tenant) ID that you copied when you registered the add-in."
However there is no ida:Issuer in the config file anymore

Secondly,
When loading the addin word/excel was telling me it could not reach the addin so I loaded it in a browser and got
"Could not find a part of the path {location of solution}\bin\roslyn\csc.exe"
Using Popo's solution from 
https://stackoverflow.com/questions/32780315/could-not-find-a-part-of-the-path-bin-roslyn-csc-exe
to uninstall the nuget package Microsoft.CodeDom.Providers.DotNetCompilerPlatform sorted it out for me.

Lastly,
With the old sample I never had to sign in for the addin if I was signed in to the host application. With the new sample even if I am signed in to the host I have to sign into the addin as well.

**Comment by Rick-Kirkham** [comment]
I'll take a closer look when I get a chance. In the meantime,
1, The error with roslyn/csc.exe is usually fixed by running Clean Solution and then Build Solution from the Build menu. But sometimes you have to do something more drastic.
2. If you are logged into Office and still get the prompt, then the add-in has failed to get the SSO token or failed to exchanged it for the access token and the code has branched to a non-SSO path that requires a login. You need to see what error is being returned by the call of getAccesstoken.
3. I'll try to reproduce the OWIN issue.

**Comment by Rick-Kirkham** [comment]
I've removed the obsolete step from the Readme.

**Comment by Rick-Kirkham** [comment]
I tried switching to single tenant, I also got an auth failure. After a lot of study of Fiddler traces and MSAL.NET docs, I figured out how to make it work. There are a number of non-obvious places where you have to put the tenant ID to ensure that the tenant-specific endpoints for discovery, well-known, and token are used instead of the "\common" endpoints. Long story short, MSAL.NET hard codes the "\common" authority (and just ignores all your config settings for the tenant-specific authority) in the ConfidentialClientApplication object. You have to explicitly set the cca.Authority to the tenant-specific URL.

Until I discovered this, when the cca.AcquireTokenOnBehalfOf() executes, I could see in Fiddler that there is are calls to the "/common" discovery, well-known, and token endpoints. This results in error 

```
ExceptionMessage=AADSTS50194: Application 'ce799661-8037-4463-ae8d-c11528956aa5'
(Office-Add-in-ASPNET-SSO) is not configured as a multi-tenant application. 
Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. 
Use a tenant-specific endpoint or configure the application to be multi-tenant.
```
This error triggers the fallback (non-SSO) auth path, so the user is prompted to login even if he/she is already logged into Office. 

I think something similar must be what's happening to you. You indicated that it works when you switch to UseWindowsAzureActiveDirectoryBearerAuthentication, but if it is working and you are logged into Office with a user in the tenant, then you wouldn't get the login prompt. So, I think the GET values controller is probably not working with UseWindowsAzureActiveDirectoryBearerAuthentication either, although it may be failing at a later point. 

Also, my understanding of the difference between UseOAuthBearerAuthentication and UseWindowsAzureActiveDirectoryBearerAuthentication is that the former is for the AAD V2 endpoint and the latter is for the V1 endpoint. V2 is needed for an add-in to support both Organization accounts and Microsoft Accounts. Also, the MSAL.NET library that the sample uses, is for the V2 endpoint.

I will try to push a version that can use single-tenant in the next few days.

**Comment by RusselRillema** [comment]
That's awesome. Thanks so much for all the feedback. Really appreciate it!
What you are saying actually makes complete sense.
Thanks again!

**Comment by Rick-Kirkham** [comment]
Just pushed change that makes it very easy to switch to single tenant. Just paste the tenant ID over the term "common" in one place in the web.config. See the readme for details. That's all there is to it.

**Comment by RusselRillema** [comment]
Legend, thank you!

**Comment by RusselRillema** [comment]
I have tested this code and for some reason I still get 401 on the values controller unless I add UseWindowsAzureActiveDirectoryBearerAuthentication
But the constant popup has been resolved which was my main concern so that you!

**Comment by RusselRillema** [comment]
Hi Rick
I think there is still a bug in the documentation you have here under the single tenant part.
You set the ValidAudience to the value of the Authority key in the web config file. This is why I was failing to authenticate when trying to git my controller.
I have changed this to be "api://localhost:44355/{ClientID}" and it works great.
Sorry, I didn't want to create a new issue if I was on the wrong track but it worked for me.
Again, thanks for all your help with this.
Cheers

**Comment by Rick-Kirkham** [comment]
It was working for me, but I'll try to take a look. Can you share the code that works and the code that doesn't? I want to be sure I understand the differences.
BTW, it looks to me like the code sets ValidAudience to the _Audience_ key in web.config, not the _Authority_ key. Is that what you meant?

**Comment by RusselRillema** [comment]
Appologies, yes. That was a typo
I have forked your project and added a brand called addingValidAudienceToConfig
https://github.com/RusselRillema/Office-Add-in-ASPNET-SSO/tree/addingValidAudienceToConfig

You'll see in the Startup.Auth.cs I have added a comment showing the results from the two different values set as ValidAudience

Let me know if you'd like me to add anything else.

For my part you can close this issue if you can't replicate. Setting this value has solved my issue.

On a side note, if I am not logged in I don't get prompted to log in. It just keeps adding 
No one is signed into Office. But you can use many of the add-ins functions anyway. If you want to log in, press the Get OneDrive File Names button again.
below point 3 until I manually log into office again.

**Comment by Rick-Kirkham** [comment]
I'm going to close this because its not a blocking issue for the OP and its more a matter of curiosity why the OP gets different behavior than others with the sample.
