### ISSUE TITLE
getAccessTokenAsync returns error 13007

### ISSUE THREAD

**Issue by mingweiw** [OfficeDev/Office-Add-in-ASPNET-SSO#4]
When I click "Get My Files from OneDrive" I get an error, see screenshot below. My Office version is 1707 (Build 8319.1000 Click-to-Run). I'm running VS 2017 Preview Version 15.3.0 Preview 3.0. This is the current preview version of VS according to [this](https://www.visualstudio.com/en-us/news/releasenotes/vs2017-preview-relnotes).

Thanks.

![image](https://user-images.githubusercontent.com/19695895/27938096-9e1d9156-6270-11e7-8782-43f21e5fa2e1.png)

**Comment by Rick-Kirkham** [comment]
@mingweiw 
13007 means that the PowerPoint cannot get an access token to your add-in's web app. Sometimes this is because there's a problem with the system itself, but since I was working with this same sample at about the same time you filed this issue and the sample was working, I think the system is fine. The problem is more likely in the way that the add-in is registered. You must log into the registration portal with the credentials of an admin of an O365 tenancy (an ---@---.onmicrosoft.com ID) when you register the app. (Use that same ID to perform the admin consent step, although that step is not what's causing your 13007.) Also, when you log into Office, you have to use an ID of some user in that same O365 tenancy.

Also, I uploaded a new version of the sample late yesterday. Please switch to the new version or you will encounter a different error after you get past the 13007 error.

**Comment by mingweiw** [comment]
I updated to the new version. It still didn't work. It turns out the reason is because I was logging into Office with my MS corp account which I also made an admin in my own tenant. That doesn't work. I tried logging into Office with a MSA user that's also an admin in my tenant. That didn't work either. I get a 13003. I finally created another AAD user in my tenant and that worked!

Thanks for the pointers!
