### ISSUE TITLE
Support for Office Online

### ISSUE THREAD

**Issue by imaksikkar** [OfficeDev/Office-Add-in-ASPNET-SSO#8]
I remember reading at some point in the walkthrough for this sample that this feature in its preview state will only work for desktop Office, not for Office Online. I can't find where I read that now, but is that still the case? And if so, is support for Office Online planned and what's the time frame on that?

**Comment by Rick-Kirkham** [comment]
You are thinking of the first Note in [SSO in Office Add-ins](https://dev.office.com/docs/add-ins/develop/sso-in-office-add-ins). Support for Office Online is planned. As an MS employee, I'm not allowed to promise future features, but the [Ignite 2017 Conference](https://www.microsoft.com/en-us/ignite/default.aspx) is coming up and there are always a lot of announcements at conferences. 

Since Office Online is a service and changes are rolled out to the cloud servers over time, it is possible that it will work for you in Office Online now.
